FROM tiangolo/uwsgi-nginx-flask:flask

MAINTAINER dev "7_main_app@eg.com"
RUN apt-get update -y
#RUN apt-get install -y python-pip python-dev build-essential
RUN pip install --upgrade pip
RUN pip install gunicorn

COPY src/sites/main_app/main_app/ .

ADD src/sites/main_app/main_app/requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

EXPOSE 5000

ENTRYPOINT ["python"]
CMD ["manage.py", "runserver", "-h", "0.0.0.0" ]
