FROM python:2.7.10

RUN apt-get -y update && apt-get install -y \
	graphviz

## install Python modules needed by the Python app
COPY ./src/calcs/requirements.txt /usr/src/app/
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r /usr/src/app/requirements.txt
RUN pip install pygraphviz --install-option="--include-path=/usr/include/graphviz" --install-option="--library-path=/usr/lib/graphviz/" --upgrade --force-reinstall

VOLUME /mr

ENV INI=/usr/ini
ENV LOG=/mr/log

COPY ./src/calcs/calc_gbp_usd_eur/*.py /usr/src/
RUN mkdir /usr/ini
COPY ./ini/logging_config_calc_gbp_usd_eur.ini /usr/ini/

RUN ls -l /usr/ini

RUN mkdir /mr/data
RUN mkdir /mr/log

#COPY ./ini/logging_config_calc_gbp_usd_eur.ini /mr/ini/logging_config_calc_gbp_usd_eur.ini
#COPY ./ini/logging_config_calc_gbp_usd_eur.ini /mr/log/logging_config_calc_gbp_usd_eur.ini
#COPY ./ini/logging_config_calc_gbp_usd_eur.ini /mr/data/logging_config_calc_gbp_usd_eur.ini
CMD ["python", "/usr/src/calc_gbp_usd_eur.py"]
