version: '2'

services:

  # 3
  calc_gbp_usd_eur:
    image: markhallett/calc_gbp_usd_eur
    environment:
           - MR_RABITMQ=${MR_RABITMQ}
           - INI=/usr/ini
    volumes:
            - "/tmp/mr:/mr"

  # 4
  mq2rest:
    image: markhallett/mq2rest
    network_mode: "host"
    environment:
           - MR_RABITMQ=${MR_RABITMQ}
    volumes:
           - "/tmp/mr:/mr"

  # 5
  rest2web:
    image: markhallett/rest2web
    ports:
        - "8888:8888"
    volumes:
        - "/tmp/mr:/mr"


  #6
  gbp_usd_eur_app:
    image: markhallett/gbp_usd_eur_app
    ports:
         - "5001:5001"
    volumes:
           - "/tmp/mr:/mr"

  # 7
  app:
    image: markhallett/app
    environment:
           - GMAIL_USERNAME=${GMAIL_USERNAME}
           - GMAIL_PASSWORD=${GMAIL_PASSWORD}
           - SECRET_KEY=${SECRET_KEY}
           - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
    ports:
         - "5000:5000"
    volumes:
           - "/tmp/mr:/mr"


networks:
   hostnet:

volumes:
    mr:
