version: '2'

services:

  # 3
  calc_gbp_usd_eur:
    image: markhallett/calc_gbp_usd_eur
    environment:
           - MR_RABITMQ=${MR_RABITMQ}
           - INI=/usr/ini
    volumes:
            - "mr:/mr"

  # 4
  mq2rest:
    image: markhallett/mq2rest
    #ports:
    #      - "5001:5001"
    #networks:
    #    hostnet: {}
    network_mode: "host"
    environment:
           - MR_RABITMQ=${MR_RABITMQ}
    volumes:
           - "mr:/mr"

  # 5
  rest2web:
    image: markhallett/rest2web
    ports:
        - "8888:8888"
    volumes:
        - "mr:/mr"

        
  #6
  gbp_usd_eur_app:
    image: markhallett/gbp_usd_eur_app
    ports:
         - "5001:5001"
    volumes:
           - "mr:/mr"

  # 7
  app:
    image: markhallett/myapp
    environment:
           - GMAIL_USERNAME=${GMAIL_USERNAME}
           - GMAIL_PASSWORD=${GMAIL_PASSWORD}
    ports:
         - "5000:5000"
    volumes:
           - "mr:/mr"


networks:
   hostnet:

volumes:
    mr:
